### ISSUE TITLE
cannot comment

### ISSUE THREAD

**Issue by RalphBike** [calderacc/fahrradstadt#79]
commenting fails on https://fahrradstadt.hamburg/faltrad-1762# with the following error message.

commentsTypeError: Module is not a constructor
    at Fahrradstadt.js?version=0.25:6
    at Object.execCb (require.js?version=0.25:30)
    at ea.check (require.js?version=0.25:18)
    at ea.<anonymous> (require.js?version=0.25:23)
    at require.js?version=0.25:8
    at require.js?version=0.25:24
    at x (require.js?version=0.25:7)
    at ea.emit (require.js?version=0.25:24)
    at ea.check (require.js?version=0.25:20)
    at ea.<anonymous> (require.js?version=0.25:23)

**Comment by maltehuebner** [comment]
Hope to be fixed in #80

**Comment by RalphBike** [comment]
Can I do a retest already? At the moment I can not comment, but get new console messages.

Edit: Error Messages appear when loading the pages. No error message when trying to comment. The button seems dead.

**Comment by maltehuebner** [comment]
@RalphBike Which browser are you using?

**Comment by RalphBike** [comment]
Chrome and Firefox on Linux and Win7. Cache has been cleared before.

**Comment by RalphBike** [comment]
Ha. If clicking on that weird mathematical symbol, I can comment. If I click the Speech balloon, nothing happens. So this has now turned into a web-to-human-interface topic, not a technical bug anymore. Well... your call if or how to proceed here :)
